defaults:
  - preprocess: default
  - dataset: librispeech_b64
  - model: fsq18k
  - train: codecslime_melt_n210
  - _self_

log_dir: /home/morg/students/dortirosh/audio_ml_tau_final/backbones/checkpoints/melt-fsq18k-n210
backbone_ckpt: /home/morg/students/dortirosh/audio_ml_tau_final/backbones/checkpoints/fsq18k-300k/last.ckpt
debug: false
ckpt: null
input_dir: null
output_dir: null

hydra:
  output_subdir: hydra
  job:
    chdir: True
