defaults:
  - preprocess: default
  - dataset: librispeech
  - model: vq8k
  - train: codecslime_cool
  - _self_

log_dir: backbones/checkpoints/cool-vq8k-from-backbone-100k
backbone_ckpt: backbones/checkpoints/vq8k-300k/last.ckpt
debug: false
ckpt: null
input_dir: null
output_dir: null

hydra:
  output_subdir: hydra
  job:
    chdir: True
